language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - "psql -c 'create database db/my_database_test;' -U postgres"
  - "bundle exec rake db:migrate"
script:
  - bundle exec rubocop --config .rubocop.yml app/ spec/ db/migrate
  - bundle exec rspec